### ISSUE TITLE
關於 const 的狀況

### ISSUE THREAD

**Issue by madeinfree** [yan771012/node-allpay-logistics#1]
Hi, @yan771012 
[src/allpay.js/#L14](https://github.com/yan771012/node-allpay-logistics/blob/master/src/allpay.js#L14)

``` javascript
const CONFIG = {
  merchantID: "",
  hashKey: "",
  hashIV: "",
  production: false,
  initialized: false
};
```

這裡的 object 用 const 不使用 let 的原因是什麼呢 ? 因為看下面還有會變更到這個 object

``` javascript
CONFIG.merchantID = merchantID;
CONFIG.hashKey = hashKey;
CONFIG.hashIV = hashIV;
```

我自己的使用上是覺得好像不太妥當～不過我也不能太確定，想討論一下～

Edit: 
看了一下文件，又或是這個 const 在 object 來說，只是確保這 object 之中的 (keys) 是不可被更動(增加或刪除)的，但 key 中的 value 是可被更動的呢？

**Comment by yan771012** [comment]
其實使用const來宣告object，仍然可以改變key。

以下操作仍可以成功

``` js
delete CONFIG. merchantID  //true
CONFIG.addKey = 'Hello'
```

const只能確保CONFIG參考object無法被更改，
但其object是可以被做任意操作的，
其實整體上來說在此宣告const或let都並無太大差異。
在此宣告成const是為了讓閱讀或編寫上可以更清楚，
CONFIG物件是全域的變數(或亦常數？)，很重要的數值操作要小心。

我翻閱了一下[MDN const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)文件，開頭寫道

The const declaration creates a read-only reference to a value. **It does not mean the value it holds is immutable, just that the variable identifier cannot be reassigned.**

如有更好意見歡迎提供，不吝賜教。

**Comment by madeinfree** [comment]
Modified this issue in https://github.com/yan771012/node-allpay-logistics/commit/053ba221afbaab5a2381950d5480306f8b8a8354, I'll close this.

#closes

**Comment by madeinfree** [comment]
原本打算關閉，不過我覺得還是開著這個討論，隨時都可以談論一下這事情。
